package iuh.fit.userservice.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ErrorCode {

    // ========== GENERAL ==========
    UNCATEGORIZED_EXCEPTION(9999, "UNCATEGORIZED_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_REQUEST(1000, "INVALID_REQUEST", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(1001, "UNAUTHORIZED", HttpStatus.FORBIDDEN),
    UNAUTHENTICATED(1002, "UNAUTHENTICATED", HttpStatus.UNAUTHORIZED),

    // ========== USER ==========
    USER_NOT_FOUND(1100, "USER_NOT_FOUND", HttpStatus.NOT_FOUND),
    USER_NOT_ACTIVE(1101, "USER_NOT_ACTIVE", HttpStatus.FORBIDDEN),
    USER_BLOCKED(1102, "USER_BLOCKED", HttpStatus.FORBIDDEN),
    ACCOUNT_DELETED(1103, "ACCOUNT_DELETED", HttpStatus.GONE),
    ACCOUNT_CAN_BE_RESTORED(6099, "ACCOUNT_CAN_BE_RESTORED", HttpStatus.BAD_REQUEST),

    // ========== AUTHENTICATION ==========
    INVALID_CREDENTIALS(1200, "INVALID_CREDENTIALS", HttpStatus.UNAUTHORIZED),
    PASSWORD_NOT_SET(1201, "PASSWORD_NOT_SET", HttpStatus.BAD_REQUEST),
    PASSWORD_ALREADY_SET(1202, "PASSWORD_ALREADY_SET", HttpStatus.BAD_REQUEST),
    INCORRECT_PASSWORD(1203, "INCORRECT_PASSWORD", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_SAME_AS_OLD(1204, "NEW_PASSWORD_SAME_AS_OLD", HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(1205, "PASSWORD_REQUIRED", HttpStatus.BAD_REQUEST),

    // ========== VALIDATION ==========
    INVALID_PHONE_FORMAT(1300, "INVALID_PHONE_FORMAT", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_FORMAT(1301, "INVALID_EMAIL_FORMAT", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_FORMAT(1302, "INVALID_PASSWORD_FORMAT", HttpStatus.BAD_REQUEST),
    INVALID_FULL_NAME(1303, "INVALID_FULL_NAME", HttpStatus.BAD_REQUEST),
    INVALID_DATE_OF_BIRTH(1304, "INVALID_DATE_OF_BIRTH", HttpStatus.BAD_REQUEST),
    INVALID_AVATAR_URL(1305, "INVALID_AVATAR_URL", HttpStatus.BAD_REQUEST),
    INVALID_COVER_URL(1306, "INVALID_COVER_URL", HttpStatus.BAD_REQUEST),
    BIO_TOO_LONG(1307, "BIO_TOO_LONG", HttpStatus.BAD_REQUEST),
    FULL_NAME_REQUIRED(1308, "FULL_NAME_REQUIRED", HttpStatus.BAD_REQUEST),

    // ========== DUPLICATE / CONFLICT ==========
    PHONE_ALREADY_EXISTS(1400, "PHONE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    EMAIL_ALREADY_EXISTS(1401, "EMAIL_ALREADY_EXISTS", HttpStatus.CONFLICT),
    PHONE_ALREADY_LINKED(1402, "PHONE_ALREADY_LINKED", HttpStatus.BAD_REQUEST),
    EMAIL_ALREADY_LINKED(1403, "EMAIL_ALREADY_LINKED", HttpStatus.BAD_REQUEST),
    EMAIL_MISMATCH(1404, "EMAIL_MISMATCH", HttpStatus.BAD_REQUEST),
    PHONE_AND_EMAIL_REQUIRED(1070, "PHONE_AND_EMAIL_REQUIRED", HttpStatus.BAD_REQUEST),
    PHONE_MISMATCH(1071, "PHONE_MISMATCH", HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(1406, "EMAIL_REQUIRED", HttpStatus.BAD_REQUEST),

    // ========== OTP ==========
    OTP_NOT_FOUND(1500, "OTP_NOT_FOUND", HttpStatus.NOT_FOUND),
    OTP_EXPIRED(1501, "OTP_EXPIRED", HttpStatus.BAD_REQUEST),
    OTP_ALREADY_USED(1502, "OTP_ALREADY_USED", HttpStatus.BAD_REQUEST),
    INVALID_OTP_CODE(1503, "INVALID_OTP_CODE", HttpStatus.BAD_REQUEST),
    OTP_MAX_ATTEMPTS_EXCEEDED(1504, "OTP_MAX_ATTEMPTS_EXCEEDED", HttpStatus.TOO_MANY_REQUESTS),
    OTP_RATE_LIMIT_EXCEEDED(1234, "OTP_RATE_LIMIT_EXCEEDED", HttpStatus.BAD_REQUEST),
    OTP_BLOCKED(1506, "OTP_BLOCKED", HttpStatus.TOO_MANY_REQUESTS),

    // ========== 2FA ==========
    TWO_FACTOR_AUTH_ALREADY_ENABLED(1601, "TWO_FACTOR_AUTH_ALREADY_ENABLED", HttpStatus.BAD_REQUEST),
    TWO_FACTOR_AUTH_NOT_ENABLED(1602, "TWO_FACTOR_AUTH_NOT_ENABLED", HttpStatus.BAD_REQUEST),

    // ========== SESSION ==========
    SESSION_NOT_FOUND(1800, "SESSION_NOT_FOUND", HttpStatus.NOT_FOUND),

    // ========== UPDATE ==========
    SAME_EMAIL(2100, "SAME_EMAIL", HttpStatus.BAD_REQUEST),
    SAME_PHONE(2101, "SAME_PHONE", HttpStatus.BAD_REQUEST),

    // ========== VALIDATION & BACKUP CODE ==========
    VALIDATION_FAILED(1111, "VALIDATION_FAILED", HttpStatus.BAD_REQUEST),
    BACKUP_CODE_EXHAUSTED(1235, "BACKUP_CODE_EXHAUSTED", HttpStatus.BAD_REQUEST),
    INVALID_BACKUP_CODE(1236, "INVALID_BACKUP_CODE", HttpStatus.BAD_REQUEST),

    INTERNAL_SERVICE_ERROR(1237, "INTERNAL_SERVICE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    INVALID_FILE(400, "FILE_001", HttpStatus.BAD_REQUEST),

    UNSUPPORTED_FILE_TYPE(400, "FILE_002", HttpStatus.BAD_REQUEST),

    PHOTO_NOT_FOUND(400, "PHOTO_001", HttpStatus.NOT_FOUND),

    PHOTO_LIMIT_EXCEEDED(400, "PHOTO_002", HttpStatus.BAD_REQUEST),
    ;



    private final int code;
    private final String message;
    private final HttpStatusCode statusCode;

    ErrorCode(int code, String message, HttpStatusCode statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }
}