package iuh.fit.authservice.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

    // Common
    UNCATEGORIZED_EXCEPTION(9999, "UNCATEGORIZED_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(1001, "INVALID_KEY", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1006, "UNAUTHENTICATED", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1007, "UNAUTHORIZED", HttpStatus.FORBIDDEN),
    INVALID_REQUEST(1008, "INVALID_REQUEST", HttpStatus.BAD_REQUEST),

    // User
    USER_NOT_EXISTED(1002, "USER_NOT_EXISTED", HttpStatus.NOT_FOUND),
    USER_NOT_ACTIVE(1003, "USER_NOT_ACTIVE", HttpStatus.FORBIDDEN),
    USER_BLOCKED(1004, "USER_BLOCKED", HttpStatus.FORBIDDEN),
    ACCOUNT_DELETED(1005, "ACCOUNT_DELETED", HttpStatus.GONE),
    ACCOUNT_CAN_BE_RESTORED(1009, "ACCOUNT_CAN_BE_RESTORED", HttpStatus.CONFLICT),

    // Auth
    INCORRECT_PASSWORD(2001, "INCORRECT_PASSWORD", HttpStatus.BAD_REQUEST),
    PASSWORD_ALREADY_SET(2002, "PASSWORD_ALREADY_SET", HttpStatus.CONFLICT),
    INVALID_PASSWORD_FORMAT(2003, "INVALID_PASSWORD_FORMAT", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_SAME_AS_OLD(2004, "NEW_PASSWORD_SAME_AS_OLD", HttpStatus.BAD_REQUEST),
    TOKEN_INVALID(2005, "TOKEN_INVALID", HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(2006, "TOKEN_EXPIRED", HttpStatus.UNAUTHORIZED),

    // Registration / Duplicate
    PHONE_ALREADY_EXISTS(3001, "PHONE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    EMAIL_ALREADY_EXISTS(3002, "EMAIL_ALREADY_EXISTS", HttpStatus.CONFLICT),
    GOOGLE_ACCOUNT_ALREADY_LINKED(3003, "GOOGLE_ACCOUNT_ALREADY_LINKED", HttpStatus.CONFLICT),

    // OTP
    OTP_NOT_FOUND(4001, "OTP_NOT_FOUND", HttpStatus.NOT_FOUND),
    OTP_ALREADY_USED(4002, "OTP_ALREADY_USED", HttpStatus.CONFLICT),
    OTP_EXPIRED(4003, "OTP_EXPIRED", HttpStatus.GONE),
    OTP_MAX_ATTEMPTS(4004, "OTP_MAX_ATTEMPTS", HttpStatus.TOO_MANY_REQUESTS),
    OTP_RATE_LIMIT(4005, "OTP_RATE_LIMIT", HttpStatus.TOO_MANY_REQUESTS),
    OTP_INVALID(4006, "OTP_INVALID", HttpStatus.BAD_REQUEST),

    // Validation
    INVALID_PHONE_FORMAT(5001, "INVALID_PHONE_FORMAT", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_FORMAT(5002, "INVALID_EMAIL_FORMAT", HttpStatus.BAD_REQUEST),
    PHONE_AND_EMAIL_REQUIRED(5003, "PHONE_AND_EMAIL_REQUIRED", HttpStatus.BAD_REQUEST),
    FULL_NAME_REQUIRED(5004, "FULL_NAME_REQUIRED", HttpStatus.BAD_REQUEST),
    INVALID_FULL_NAME(5005, "INVALID_FULL_NAME", HttpStatus.BAD_REQUEST),

    // Google
    GOOGLE_AUTH_FAILED(6001, "GOOGLE_AUTH_FAILED", HttpStatus.BAD_REQUEST),
    GOOGLE_TOKEN_INVALID(6002, "GOOGLE_TOKEN_INVALID", HttpStatus.BAD_REQUEST),

    // Session
    SESSION_NOT_FOUND(7001, "SESSION_NOT_FOUND", HttpStatus.NOT_FOUND),

    // QR Code
    QR_CODE_NOT_FOUND(8001, "QR_CODE_NOT_FOUND", HttpStatus.NOT_FOUND),
    QR_CODE_EXPIRED(8002, "QR_CODE_EXPIRED", HttpStatus.GONE),
    INVALID_QR_CODE(8003, "INVALID_QR_CODE", HttpStatus.BAD_REQUEST),
    QR_CODE_ALREADY_USED(8004, "QR_CODE_ALREADY_USED", HttpStatus.CONFLICT),
    INVALID_QR_STATUS(8005, "INVALID_QR_STATUS", HttpStatus.BAD_REQUEST),
    INVALID_DEVICE_ID(8006, "INVALID_DEVICE_ID", HttpStatus.BAD_REQUEST),
    TOO_MANY_PENDING_QR_LOGINS(8007, "TOO_MANY_PENDING_QR_LOGINS", HttpStatus.TOO_MANY_REQUESTS),

    // Email
    EMAIL_SEND_FAILED(9001, "EMAIL_SEND_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // Internal
    INTERNAL_SERVICE_ERROR(9998, "INTERNAL_SERVICE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    INVALID_BACKUP_CODE(9999, "INVALID_BACKUP_CODE", HttpStatus.BAD_REQUEST);

    private final int code;
    private final String message;
    private final HttpStatus httpStatus;

    ErrorCode(int code, String message, HttpStatus httpStatus) {
        this.code = code;
        this.message = message;
        this.httpStatus = httpStatus;
    }
}