spring.application.name=mediaServices

# Server Configuration
server.port=8080
server.servlet.context-path=/media/api

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-calm-waterfall-a1v4nq7x-pooler.ap-southeast-1.aws.neon.tech/db_social?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8retqHOipvf5
spring.datasource.driver-class-name=org.postgresql.Driver


# Naming stategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB



# Redis Server Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=your_password_if_any

# Lettuce Connection Pool Settings
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=1000ms

# C?u hình cache (Tùy ch?n)
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
