services:

  media-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy # Đợi Redis Ping thành công rồi app mới chạy
    environment:
      # Ghi đè localhost trong application.properties thành tên container redis
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - media-network

  redis:
    image: redis:latest
    container_name: redis-media-service
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ""
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - media-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - media-network

volumes:
  redis-data:
    driver: local

networks:
  media-network:
    driver: bridge