spring.application.name=mediaServices

spring.datasource.url=jdbc:postgresql://ep-calm-waterfall-a1v4nq7x-pooler.ap-southeast-1.aws.neon.tech/db_social?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8retqHOipvf5
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

