spring.application.name=mediaServices

# Server Configuration
server.port=8080
server.servlet.context-path=/media/api

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-calm-waterfall-a1v4nq7x-pooler.ap-southeast-1.aws.neon.tech/db_social?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8retqHOipvf5
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Logging Configuration
logging.level.mediaservice=DEBUG
logging.level.mediaservice.services.impl.PostServiceImpl=DEBUG
logging.level.mediaservice.services.impl.CloudinaryServiceImpl=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dpmyobtz3}
cloudinary.api-key=${CLOUDINARY_API_KEY:315392974264551}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:4nnHO8B9_pgin7o0elR1bLXH-Iw}

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

